// Copyright (c) 2014-2025 Sarin Na Wangkanai, All Rights Reserved.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Wangkanai.EntityFramework.Postgres;

/// <summary>
/// Provides extension methods for configuring PostgreSQL-specific behaviors on Entity Framework Core properties.
/// </summary>
public static class ConfigurationExtensions
{
   private const string Now = "NOW()";

   /// <summary>
   /// Configures a property to use the PostgreSQL "NOW()" function as the default value and
   /// to generate its value only when a new entity is added.
   /// </summary>
   /// <typeparam name="T">The type of the property being configured.</typeparam>
   /// <param name="builder">The property builder used to configure the property.</param>
   public static void NpgValueGeneratedOnAdd<T>(this PropertyBuilder<T> builder)
   {
      builder.HasDefaultValueSql(Now);
      builder.ValueGeneratedOnAdd();
   }

   /// <summary>
   /// Configures a property to use the PostgreSQL "NOW()" function as the default value and
   /// to generate its value whenever an existing entity is updated.
   /// </summary>
   /// <typeparam name="T">The type of the property being configured.</typeparam>
   /// <param name="builder">The property builder used to configure the property.</param>
   public static void NpgValueGeneratedOnUpdate<T>(this PropertyBuilder<T> builder)
   {
      builder.HasDefaultValueSql(Now);
      builder.ValueGeneratedOnUpdate();
   }

   /// <summary>
   /// Configures a property to use the PostgreSQL "NOW()" function as the default value and
   /// to generate its value both when a new entity is added and whenever an existing entity is updated.
   /// </summary>
   /// <typeparam name="T">The type of the property being configured.</typeparam>
   /// <param name="builder">The property builder used to configure the property.</param>
   public static void NpgValueGeneratedOnAddOrUpdate<T>(this PropertyBuilder<T> builder)
   {
      builder.HasDefaultValueSql(Now);
      builder.ValueGeneratedOnAddOrUpdate();
   }

   /// <summary>
   /// Configures a property to never have its value generated by the database.
   /// </summary>
   /// <typeparam name="T">The type of the property being configured.</typeparam>
   /// <param name="builder">The property builder used to configure the property.</param>
   public static void NpgValueGeneratedNever<T>(this PropertyBuilder<T> builder)
   {
      builder.ValueGeneratedNever();
   }
}